### ISSUE TITLE
cant start app

### ISSUE THREAD

**Issue by wx5050520** [flash168/Peach#3]
数据源地址/嗅探服务地址 怎么配置，启动不了

**Comment by GitClound** [comment]
同问如何配置地址

**Comment by flash168** [comment]
此程序根据tvbox数据源编写的播放器，配置数据源地址可使用drpy或重构版hipy服务https://github.com/hjdhnx/hipy-ui，嗅探服务可使用[hipy-sniffer](https://github.com/hjdhnx/hipy-sniffer)。详细使用请自行探索。
